### ISSUE TITLE
Changes for Compatibility with target-postgres

### ISSUE THREAD

**Issue by acarter24** [Matatika/tap-googleads#12]
Not sure this qualifies as an issue/bug report, just a note that might be useful for others.

To get compatibility with `target-postgres` pipelinewise variant:

- Set the `data_flattening_max_level` on the target config to at least 3.
- Change the primary keys through the `metadata` key in meltano.yaml, mostly to remove whitespace and adjust capitalisation. i.e. `ad_group_criterion__age_range__type` becomes `adGroupCriterion__ageRange__type`.

```
  - name: tap-googleads
    variant: matatika
    pip_url: git+https://github.com/matatika/tap-googleads
    config:
      oauth_credentials.client_id: ${TAP_GOOGLEADS_CLIENT_ID}
      oauth_credentials.client_secret: ${TAP_GOOGLEADS_CLIENT_SECRET}
      oauth_credentials.refresh_token: ${TAP_GOOGLEADS_REFRESH_TOKEN}
      customer_id: ${TAP_GOOGLEADS_CUSTOMER_ID}
      developer_token: ${TAP_GOOGLEADS_DEVELOPER_TOKEN}
      start_date: '2023-01-01T00:00:00Z'
    metadata:
      stream_accessible_customers:
        key-properties:
          - resourceNames
      stream_customer_hierarchy:
        key-properties:
          - customerClient__id
      stream_geo_target_constant:
        key-properties:
          - geoTargetConstant__id
      stream_adgroups:
        key-properties:
          - adGroup__id
          - adGroup__campaign
          - adGroup__status
      stream_adgroupsperformance:
        key-properties:
          - campaign__id
          - adGroup__id
      stream_campaign_performance_by_age_range_and_device:
        key-properties:
          - adGroupCriterion__ageRange__type
          - campaign__name
          - segments__date
          - campaign__status
          - segments__device
      stream_campaign_performance_by_gender_and_device:
        key-properties:
          - adGroupCriterion__gender__type
          - campaign__name
          - segments__date
          - campaign__status
          - segments__device
      stream_campaign_performance_by_location:
        key-properties: 
          - campaignCriterion__location__geoTargetConstant
          - campaign__name
          - segments__date
      stream_geo_performance:
        key-properties: 
          - geographicView__countryCriterionId
          - customer_id
          - campaign__name
          - segments__date
```
